apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  dbconfig: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjExMTExMTExQG15ZGF0YWJhc2UuYzdxb2lkdmxpazZ0LmV1LWNlbnRyYWwtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL215ZGI=
